### ISSUE TITLE
Configurable user name

### ISSUE THREAD

**Issue by sitina** [am-gd-cz/opsutil-tests#1]
As I'm having different user name on my laptop, it would be great to have a chance to setup custom user name for connection to PI/instances; I'll try to prepare PR with fix for that.

**Comment by sitina** [comment]
.. with remote_user stuff

**Comment by am-gd-cz** [comment]
https://github.com/am-gd-cz/opsutil-tests/commit/fe950d029eccffc7a710e658efd52ce17a268dc9#diff-04c6e90faac2675aa89e2176d2eec7d8R26
